name: Main Workflow

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: v1-${{ hashFiles('yarn.lock') }}-${{ hashFiles('elm.json', 'elm-tooling.json') }}
          restore-keys: |
            v1-${{ hashFiles('yarn.lock') }}-
            v1-
          path: |
            node_modules
            elm-stuff
            ~/.elm
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: yarn
      - run: yarn test
      - run: yarn elm-format --validate src/ tests/
